name: fitness_training_app
description: "AI-powered gamified fitness training app with personalized cartoon avatars"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase will be added using flutter pub add

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Networking
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.0.5

  # Animations
  lottie: ^3.1.2
  rive: ^0.13.13

  # Camera & Images
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  image: ^4.2.0

  # Subscriptions
  in_app_purchase: ^3.2.0

  # Permissions
  permission_handler: ^11.3.1

  # JSON & Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Utils
  uuid: ^4.5.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.1

  # Development
  logger: ^2.4.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.4
  json_serializable: ^6.8.0
  freezed: ^2.5.7

  # Testing
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/lottie/
