// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAby9wtr1-b714zBOi13peNYsxpHzCU8',
    appId: '1:131153934641:web:16e1323e6895798eea5810',
    messagingSenderId: '131153934641',
    projectId: 'personal-trainer-d1db2',
    authDomain: 'personal-trainer-d1db2.firebaseapp.com',
    storageBucket: 'personal-trainer-d1db2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAby9wtr1-b714zBOi13peNYsxpHzCU8',
    appId: '1:131153934641:android:16e1323e6895798eea5810',
    messagingSenderId: '131153934641',
    projectId: 'personal-trainer-d1db2',
    storageBucket: 'personal-trainer-d1db2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbAby9wtr1-b714zBOi13peNYsxpHzCU8',
    appId: '1:131153934641:ios:16e1323e6895798eea5810',
    messagingSenderId: '131153934641',
    projectId: 'personal-trainer-d1db2',
    storageBucket: 'personal-trainer-d1db2.firebasestorage.app',
    iosBundleId: 'com.fitnessapp.fitnessTrainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbAby9wtr1-b714zBOi13peNYsxpHzCU8',
    appId: '1:131153934641:ios:16e1323e6895798eea5810',
    messagingSenderId: '131153934641',
    projectId: 'personal-trainer-d1db2',
    storageBucket: 'personal-trainer-d1db2.firebasestorage.app',
    iosBundleId: 'com.fitnessapp.fitnessTrainingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbAby9wtr1-b714zBOi13peNYsxpHzCU8',
    appId: '1:131153934641:web:16e1323e6895798eea5810',
    messagingSenderId: '131153934641',
    projectId: 'personal-trainer-d1db2',
    authDomain: 'personal-trainer-d1db2.firebaseapp.com',
    storageBucket: 'personal-trainer-d1db2.firebasestorage.app',
  );
}
